### ISSUE TITLE
'function invocation took longer than 10 seconds'

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#16]
need error handling for occasional server snafu: perhaps local store of default fallbacks

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/78912983-503a5e00-7a56-11ea-907f-3d4a1babff8a.png)

**Comment by agnescameron** [comment]
ah, he returns! I'll add an error handler today
