### ISSUE TITLE
context set is 'undefined'

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#17]
every so often the context doesn't set properly, need to figure out why

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/78370882-44055b00-7595-11ea-975e-4d2b16988942.png)

**Comment by agnescameron** [comment]
oh no! my bad, I know exactly what this is. (overzealous tidying)

**Comment by agnescameron** [comment]
give me 5

**Comment by agnescameron** [comment]
ok fixed :3
