### ISSUE TITLE
can't read property 'isUser' of undefined

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#19]
bug you get by having unprocessed async responses after the app leaves the chat window. need some way to handle these

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/74478987-670c6c00-4e7c-11ea-9c39-e6db0e5cbcec.png)

**Comment by cosmicespresso** [comment]
https://github.com/Kallirroi/bot_test/commit/eba3bdbe474bc85855330a2bc4a2a8c9eba81f73
