### ISSUE TITLE
audioVis appears to keep recording after leaving the page

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#3]
or else, for some reason the thing gathering sound data keeps printing to the console:

<img width="1416" alt="Screen Shot 2020-01-29 at 17 16 08" src="https://user-images.githubusercontent.com/16444898/73402332-1234f700-42bb-11ea-8569-9952013ed407.png">

**Comment by cosmicespresso** [comment]
yes I had to operate on that npm module but maybe forgot to push - not a stable edit tho. It's on my todo list.
