### ISSUE TITLE
how to order bots 

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#38]
Round 1: bot speaks first
Round 2: user speaks first
Round 3: bot speaks first (?) or random (?)

**Comment by cosmicespresso** [comment]
@agnescameron this is sorted out right?

**Comment by agnescameron** [comment]
almost: everything's done except round 1. perhaps I'll merge the dialog branch (with shortened rounds) so everything's linked together. I can have a look at that today?

Round 1: user speaks first (with potential timeout) / random
Round 2: bot speaks first (w/ truth challenge)
Round 3: user speaks first (w/ truth challenge)

**Comment by agnescameron** [comment]
(for context) currently on master branch the correct bots aren't linked to the correct rounds. I made it so that the order of speech depends on the bot that is speaking (so we can make changes to statemap without having to change lots of other stuff)

**Comment by agnescameron** [comment]
I'm gonna close this and add round1 as a specific issue: bots now ordered correctly in all the other rounds.
