### ISSUE TITLE
sometimes bot typing time overly-long

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#42]
<img width="1043" alt="Screen Shot 2020-04-02 at 12 23 52" src="https://user-images.githubusercontent.com/16444898/78283025-31364c00-74eb-11ea-9847-0471c242be77.png">
noticed this during the bot queue debugging: we can just add a cap here, but might be good to know why the timing is getting so high. It seems to go up when you overload the bot with messages, though perhaps this is just a coincidence.

**Comment by agnescameron** [comment]
note: on a practical level, this has been resolved by adding a time threshold for bot replies. 

It might be worth looking into what was causing some of the replies to be so long (as this might also inform some approaches to `botQueue`), but this particular issue is resolved for now.

**Comment by cosmicespresso** [comment]
Should we close this? I haven't really seen it recently.

**Comment by agnescameron** [comment]
sure: it shouldn't cause any problems
