### ISSUE TITLE
where are the dots?

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#43]

**Comment by cosmicespresso** [comment]
@agnescameron the reason the dots are gone is because in Exchange.js `props.text` is never null 
![image](https://user-images.githubusercontent.com/10440556/78373411-91cf9280-7598-11ea-9c6d-a08927f0dc91.png)

I assume that makes sense because the bot seems to "have" the response before the UI displays it:  - in the image below, I see the console logging on the right approximately a second before I see the response in the UI.
![image](https://user-images.githubusercontent.com/10440556/78373603-d0fde380-7598-11ea-925b-a1eb331bb886.png)

Does that make sense?

**Comment by agnescameron** [comment]
hmmmmmm, I wonder what's different between this and the user text! i will investigate 🕵️‍♀️

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/78376001-b0835880-759b-11ea-85d5-004f51768944.png)

The promise structure looks different

**Comment by agnescameron** [comment]
ah, that's very recent: it's just cause I moved the 'send to bot' part to textProcessing rather than having it locally. no dots before that

**Comment by agnescameron** [comment]
the conversation stuff *should* all work the same, but I'll have a look!

**Comment by agnescameron** [comment]
<img width="1440" alt="Screen Shot 2020-04-03 at 11 19 17" src="https://user-images.githubusercontent.com/16444898/78376964-05739e80-759d-11ea-944f-a21046b2ef4d.png">
ok: the bot having the response isn't the problem i don't think!

**Comment by agnescameron** [comment]
(this is usertest)

**Comment by agnescameron** [comment]
ok i fixed it (but idk if this fix will be OK or not):

in Chat.js, there's a function that renders if the bot is typing. 

this is what we currently have in bot_test:
<img width="553" alt="Screen Shot 2020-04-03 at 11 23 16" src="https://user-images.githubusercontent.com/16444898/78377540-ba0dc000-759d-11ea-8e73-2ea42da98130.png">

this matches usertest, and the dots work:
<img width="507" alt="Screen Shot 2020-04-03 at 11 23 12" src="https://user-images.githubusercontent.com/16444898/78377539-b9752980-759d-11ea-9f1c-cd9d1f216d62.png">

**Comment by agnescameron** [comment]
ahhhh, this also works: 
<img width="510" alt="Screen Shot 2020-04-03 at 11 25 54" src="https://user-images.githubusercontent.com/16444898/78377679-eaedf500-759d-11ea-95dd-75a8fb8815ba.png">
