### ISSUE TITLE
setting chat round timer > 60 causes it to loop back around

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#46]
We're unlikely to want to do this so it's not really an issue per se, but wanted to check that this was expected behaviour!

59 seconds continues as normal
60 seconds loops back round to 0, then continues
61 seconds loops back round to 0, then continues

I reckon it's because of this line in `Utils.js`:

```
  var seconds = (Math.floor(time / 1000) % 60);
```

**Comment by cosmicespresso** [comment]
yep I know this - the timer isn't super reliable, might have a look at it again

**Comment by agnescameron** [comment]
yeah no worries: I can't see it causing many real problems at the moment but good to know of it

**Comment by cosmicespresso** [comment]
Good catch - essentially the `seconds` variable is never equal to 60. I think if we want to go up to a minute we can set `timeLimit: 59,` in the `StateMap.js` (it will cut it at exactly 59secs but oh well).
