### ISSUE TITLE
set timeout for bot to speak in round1 (step 5)

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#49]
In the first Chat round, we currently expect the player to initiate conversation. This is to avoid the impression that the bot is somehow 'in control' of the interaction, but we run the risk that the interaction could be very slow/awkward to start if both parties remain silent.

Thus, perhaps building in a 4-8 second timeout window, after which the bot will initiate conversation might be a good way to handle the interaction. Unsure of the do's and dont's of this WRT the current react flow but happy to look at this later this week.

**Comment by cosmicespresso** [comment]
was this in the most recent PR?

**Comment by agnescameron** [comment]
I'll check now

**Comment by agnescameron** [comment]
ok: the error first occurs when master gets merged into `dialog` pre-PR... so I have a feeling that the error has come either from a change to master, or from the combination of a change to master and a change introduced in the PR

**Comment by agnescameron** [comment]
I didn't notice at the time as the times in StateMap were very short!

**Comment by agnescameron** [comment]
oh wait omg sorry wrong issue entirely

**Comment by agnescameron** [comment]
yep!
