### ISSUE TITLE
'not very convincing' bot responses thread  🤔

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#51]
![image](https://user-images.githubusercontent.com/10440556/79020923-2d887200-7b48-11ea-8891-aaa671f31751.png)

**Comment by agnescameron** [comment]
lol

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/79153326-af240e00-7d9b-11ea-99ab-77619b7ae5d6.png)
![image](https://user-images.githubusercontent.com/10440556/79153346-b3e8c200-7d9b-11ea-89a6-d2db5ad133f8.png)

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/79169454-7fd0c980-7dba-11ea-90cb-1ea56e0046dc.png)

**Comment by agnescameron** [comment]
<img width="415" alt="Screen Shot 2020-04-14 at 10 32 46" src="https://user-images.githubusercontent.com/16444898/79236741-5c9a2e80-7e3b-11ea-8d8b-556bf2efa9b9.png">
when the bot resets ('chat more') for some reason it ends up in what i can only describe as a 'pure yang' setting

**Comment by cosmicespresso** [comment]
should we close this and only use are.na channel for now?
