### ISSUE TITLE
this.props.onInputFocus is not a function

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#52]
<img width="475" alt="Screen Shot 2020-04-15 at 10 38 32" src="https://user-images.githubusercontent.com/16444898/79350443-743de980-7f05-11ea-8273-aa3b81197e87.png">

I get this on both Chrome and Firefox: is it a package I'm missing?

**Comment by agnescameron** [comment]
NB -- got this by merging master into my branch, but I also get this error if I'm on `master`

**Comment by cosmicespresso** [comment]
Oh I just forgot to comment out some stuff - will fix soon!

**Comment by cosmicespresso** [comment]
should be fine now

**Comment by agnescameron** [comment]
<3 <3 <3 merci!
