### ISSUE TITLE
bot dots on user side at start of interaction

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#56]
<img width="510" alt="Screen Shot 2020-04-16 at 12 47 15" src="https://user-images.githubusercontent.com/16444898/79483641-8771b780-7fe0-11ea-8983-735af52e92b1.png">
they go back to the bot side after the bot first speaks

**Comment by agnescameron** [comment]
it does this at the start of all rounds where the user types first.

**Comment by cosmicespresso** [comment]
huh thats a first - unfortunately I think the `isUser` property is most likely involved here too -_-

**Comment by agnescameron** [comment]
sorry got this confused with the other issue... this first occurs in my code when I pulled master into `dialog` at 21:57 yesterday

**Comment by cosmicespresso** [comment]
~I think its my fault, fixing now~

My thoughts were either db96ae6ac1b1511a0a76d942b430036cdf9c2d88 or db96ae6ac1b1511a0a76d942b430036cdf9c2d88 were the culprits but checking them out locally doesn't seem to be the case.

**Comment by cosmicespresso** [comment]
https://github.com/Kallirroi/bot_or_not/commit/210198ad9ff5dc399a93d97d07d43e924b9e26ee
