### ISSUE TITLE
"During transition to my turn to ask questions, the screen went blank (mobile)"

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#57]
1 respondent had this issue with mobile safari (interestingly another respondent on mobile safari did not). Another respondent also had this issue on mobile but they're not in the spreadsheet so idk how to get their browser

**Comment by cosmicespresso** [comment]
I'm gonna guess this is the `isUser` bug but we have to figure out ways to handle these

**Comment by agnescameron** [comment]
im gonna nest the conditionals maybe.

**Comment by agnescameron** [comment]
not cute but also less cute to have a line that doesn't work imo

**Comment by agnescameron** [comment]
If it was the isUser bug, then this is fixed. Will re-open if no
