### ISSUE TITLE
make textProcessing into a React component

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#59]

**Comment by cosmicespresso** [comment]
On a second thought - I think this file doesn't need to be a Component, for the simple reason that it has nothing to do with the DOM. It is quite cluttered - so your initial idea of turning that into a Component is a good one - but I would just split it into two helper files, if that makes sense.

**Comment by agnescameron** [comment]
yes! I think also: I've been refactoring it instead, which will hopefully neaten it up somewhat (not sure splitting in two would help as all the functions are related and call one another...)
