### ISSUE TITLE
npm / webpack issues for bot integration

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#6]
![image](https://user-images.githubusercontent.com/10440556/73671042-42441780-4678-11ea-818e-5bcf31d0b450.png)

My version: 

![image](https://user-images.githubusercontent.com/10440556/73671064-4e2fd980-4678-11ea-9b25-7153e0a2b44a.png)

**Comment by cosmicespresso** [comment]
looks like it has to do with one of the npm packages I had to install (7d80e834241e2f555bbcd7b78e7e406935dc944e) - most likely `parcel-bundler`:

`[nodemon] starting node server.js`
`[HPM] Proxy created: /  -> http://localhost:9000`
`[HPM] Proxy rewrite rule created: "^/.netlify/functions" ~> "" `
`🚨  No entries found.`
`    at Bundler.bundle (/Users/Kallirroi/Documents/code/mozilla/bot_test/node_modules/parcel-bundler/src/Bundler.js:27`

**Comment by agnescameron** [comment]
ok so: I pulled your branch, and it runs fine (apart from some css weirdness: is it related? screenshot below). however, when I run `npm install` I get an error trying to install a module called `webworker-threads`. I'm going to look into it but perhaps this is related?

The error is perhaps related to something/ bypassing the `.env` file that's needed to run the two different versions of webpack (this is documented in basecamp [here](https://3.basecamp.com/3738366/buckets/13678386/documents/2370239341)), scroll down to 'Horrible hacks that needed to happen to make everything work'

**Comment by cosmicespresso** [comment]
I hadn't installed the keys to my `.bash_profile`
