### ISSUE TITLE
bot texting dots are patchy in rounds where bot starts

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#60]
e.g. truth challenge round: from user feedback, now bot takes the time to type their challenge, but it doesn't always get the dots

**Comment by Kallirroi** [comment]
update to this: dots appear when there's a second line coming

**Comment by cosmicespresso** [comment]
I haven't seen this yet, but will keep looking. It's separate from queue not getting cleared properly right?

**Comment by agnescameron** [comment]
I fixed this -- it turns out that there needs to be a `<Message>` object in the chat for dots to get appended... as far as I could tell, changing this would actually be pretty involved, so I've fixed this by just appending a blank message to the chat queue every time the bot wants to speak first, then the dots will follow as it types it's actual message.

It's a little hacky, but I don't think it has any adverse affects on anything else (and feels like it'll certainly be less risky than changing the messaging infrastructure).

The line (which appears in `ChooseTruth`, and `awaitUserInput`, though I might merge these into a single function) is:
```
this.appendMessage('');
```
followed by, as before:
```
this.processResponse(response); 
```
