### ISSUE TITLE
refactor timer component

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#61]
something isnt working right

**Comment by agnescameron** [comment]
It might be becuase i got it to count backwards? It wasn't causing any issues when I made the change but v possible i could have missed something

**Comment by cosmicespresso** [comment]
no I think it was a glitch with how I am resetting it, I think now its much faster.  https://github.com/Kallirroi/bot_or_not/commit/c48967a719dd6244fdef3cb63bc9856a70416008
