### ISSUE TITLE
since there is an opponent name, make the bot use that if asked "what is your name" ?

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#62]

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/80008945-61439000-8496-11ea-8b89-fc5071f22c2b.png)

not really an issue but I wanted to paste the visual

**Comment by agnescameron** [comment]
yes: this has to be handled in middleware, it's a little unsure as some of the names are things like `asdfg`, so still thinking about whether to handle that (or just to make all the names normal)

**Comment by cosmicespresso** [comment]
maybe a cheap trick is to have the bot say "well my username is right there, I can't tell you my real one" or sth

**Comment by agnescameron** [comment]
ya something like that...

**Comment by cosmicespresso** [comment]
ok closing this
