### ISSUE TITLE
advance the dialogue format from single<-->single text to multiple <--> single or multiple <---> multiple

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#64]
This is a pretty major undertaking, so while I understand its important, I think we might not have the time to do that. There is already an issue with trying to add a second line to the bot's response, which is that the dots get triggered at the wrong place (maybe something a simple CSS tweak can fix, maybe not). 
Do we want to go down that road?

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/80014588-7f14f300-849e-11ea-9411-0ff2e9435660.png)
![image](https://user-images.githubusercontent.com/10440556/80014620-8b00b500-849e-11ea-9b09-5f2af9acfa5a.png)

**Comment by agnescameron** [comment]
so right now, if there's a full stop, question mark, or exclamation point, the messages get added separately to the bot queue: so a more realistic variation can be achieved fairly cheaply that way.

~That screenshot above is actually the message queue not getting cleared properly (RIP, thought we fixed that).~

**Comment by agnescameron** [comment]
I _have_ been thinking that it would be nice not to have all the messages be 1:1 -- it's currently much easier to get the bot to randomly skip responses than to get it to add in responses out of nowhere (naturalistically that is), though there might be a way to do that too.

I think the trouble is that adding messages / knowing when to add messages requires an understanding of context that is normally on fairly shaky ground here... but perhaps there's some 'safe contexts' where the bot could have a bit more 'random' energy

**Comment by agnescameron** [comment]
this should now work!! it's still not amazing at handling multiple texts from the player (but it sucks much less than it did). also fills in awkward silences if player doesn't respond for a while
