### ISSUE TITLE
message queue not being cleared properly

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#65]
![image](https://user-images.githubusercontent.com/10440556/80125148-4ab53b80-855f-11ea-894c-18280f6e9976.png)

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/80126470-235f6e00-8561-11ea-8a0b-eb844c4c8195.png)
seems to happen quite often on Round 1 at least

**Comment by cosmicespresso** [comment]
Was this fixed?

**Comment by agnescameron** [comment]
this bug has been manually scraped from existence in the `configureChat` function, which now does a hard reset on all the messaging, queues and timeouts at the end of each Chat round.
