### ISSUE TITLE
No 'wait' screen before final truth round

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#66]
(still need to leave pause for the 'opponent' to think)

**Comment by cosmicespresso** [comment]
do I still need to do that?

**Comment by agnescameron** [comment]
one of us should; I'm also happy to~

**Comment by agnescameron** [comment]
(perhaps easier if i do / lmk when you do as a couple of numbers need to change around)

**Comment by cosmicespresso** [comment]
https://github.com/Kallirroi/bot_or_not/commit/23e51330215dbfca113ae892086cd89dca60ab47 Make sure you check things as well bc I'm not sure if the stateHelpers is correct

**Comment by agnescameron** [comment]
yeye i will: i'll do this this afternoon
