### ISSUE TITLE
Scale BOT_SPEED to how long the incoming response is (currently random)

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/bot_test#8]
^ This can't actually be done by DF directly, but I can add a programmable delay in the middleware

**Comment by cosmicespresso** [comment]
https://github.com/Kallirroi/bot_test/blob/f48af41908678bf33dc7950bf0445f7cfa8eb71a/src/Utils.js#L2

we can play with speed here

**Comment by cosmicespresso** [comment]
I added this 
```
function getRandomInt(max) {
  return Math.floor(Math.random() * Math.floor(max)+1);
}

const BOT_DELAY = 4000;
const BOT_SPEED = getRandomInt(4) * 0.001;
const BOT_MAX_CHARS = 350;
```
to introduce some variability in the answer timing - but maybe we can figure out a way to scale this with respect to how long the incoming response is?

**Comment by agnescameron** [comment]
I'm pretty sure this is already implemented, good to close? (unless I'm missing something...)
