### ISSUE TITLE
'typing' dots being displaced inwards

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#81]
@agnescameron any clues as to when that started?

![image](https://user-images.githubusercontent.com/10440556/81876007-acaa0500-954f-11ea-8b29-d4dfa8f1feb2.png)

**Comment by agnescameron** [comment]
ah hm i notice this from time to time: I remember this issue existing already but perhaps we thought it went away. I think maybe first noticed this a few weeks ago?

**Comment by cosmicespresso** [comment]
ahh this is very elusive - it only seems to happen when the bot double-texts (never when it's the first response to a user message). When did you add that functionality?

**Comment by agnescameron** [comment]
it's been there for a couple of months, but we're using it more now -- when there's punctuation in a bot's response, it splits the message in two and adds it to bot queue. It doesn't use anything special though: everything just goes through the bot queue.

recently I added in a 'line break' character that allows the bot to text over multiple lines without having punctuation to split them, which is probably why we're seeing this more.

**Comment by cosmicespresso** [comment]
ohhh ok great thats helpful - yes the \n can totally be the culprit here

**Comment by agnescameron** [comment]
ahhh it's not a \n though -- it's just appending 2 messages to the queue separately

**Comment by agnescameron** [comment]
hmmmmmmm.... what it does is splits the sentence into an array, and concatenates that to the bot queue... which is maybe not quite the same

```
  processResponse = (text) => {
    //check if message pure punctuation, let it pass if so
    if (text.match(/[a-zA-Z]/g)){
      //breaks sentences into different messages
      text = text
        .match(/[^.!?%]+[.!?]*/g)
        .map(str => str.trim());
    }
    else if (!text) {
      text = handleError();
    }

    this.botQueue = this.botQueue.concat(text);

    // random pause before the bot starts typing, as if thinking
    setTimeout(() => this.setState({isBotTyping: true}, () => 
      this.processBotQueue()), this.getRandomInt(1100, 3500));
  }
```

**Comment by agnescameron** [comment]
so the regex is looking for punctuation, or the 'newline' character `%`: if there's punctuation it splits and keeps the punctuation, if there's a `%` it splits and gets rid of the `%`.

**Comment by cosmicespresso** [comment]
ok I will play a bit with that and report back

**Comment by agnescameron** [comment]
yeah. there's also one tiny hack that I did to make the bot dots appear at the start of rounds (they only get appended once there are messages on the screen) that just appends a blank message, before the bot starts typing. but the dots aren't distorted underneath that I don't think (+ I feel like we'd already seen the dots getting displaced before that...)

that's done here:
```
      if(this.state.messages.length === 0) {
        //if start of interaction, adds a blank 
        //message to kickstart the 'bot dots'
        this.appendMessage('');
        this.processResponse(response); 
      }

```

**Comment by cosmicespresso** [comment]
^ very likely this is the reason, but I'm also investigating whether the `trim()` function you are using has the results we want (whether it creates a new variable or operates on the existing one)

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/81963682-6dc58f00-95e3-11ea-8fc8-d79f4366cf7c.png)
